### ISSUE TITLE
Indicate supported versions of dataplane and controlplane.

### ISSUE THREAD

**Issue by jrsmroz** [Kong/gateway-operator-docs#3]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

The gateway by default uses the correct version of the dataplane and controlplane images. But it's configurable and a user may end up with a setup that's actually not supported. We should at least document what versions are supported.

**Comment by ksully-execute** [comment]
where are the compatible version for use by the gateway operator listed?

**Comment by pmalek** [comment]
Hi @ksully-execute 👋 

This project is currently under heavy development and there are a lot of moving parts (which might not be visible to the public eye).

With v0.4.0 which is the latest release that currently available - https://github.com/Kong/gateway-operator/pkgs/container/gateway-operator - we currently support KIC (as `ControlPlane`) in versions 2.7+ and Kong Gateway (as `DataPlane)` 3.0.

There's been a lot of development w.r.t the these constraints internally and next release might significantly change what I just mentioned so you might want to stay tuned for that.

**Comment by ksully-execute** [comment]
Ok, thanks Patryk

**Comment by ksully-execute** [comment]
Can you give me a hint as to when we can expect something published?

 

From: ***@***.*** ***@***.***> 
Sent: Monday, June 12, 2023 7:26 AM
To: 'Kong/gateway-operator-docs' ***@***.***>
Subject: RE: [Kong/gateway-operator-docs] Indicate supported versions of dataplane and controlplane. (Issue #3)

 

Ok, thanks Patryk

**Comment by pmalek** [comment]
No ETA to disclose for now unfortunately.

**Comment by mflendrich** [comment]
> where are the compatible version for use by the gateway operator listed?

This is now covered by documentation:
https://docs.konghq.com/gateway-operator/latest/reference/version-compatibility/
